name: "Build exec"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
    build-mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install requirements
              run: |
                pip install -r devRequirements.txt
                pip install -r requirements.txt
            - name: Build
              run: pyinstaller --onefile __main__.py
            - name: Rename
              run: mv dist/__main__ release_osx
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release_osx
                  path: release_osx
    build-binbows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install requirements
              run: |
                pip install -r devRequirements.txt
                pip install -r requirements.txt
            - name: Build
              run: pyinstaller --onefile __main__.py
            - name: Rename
              run: mv dist/__main__.exe release_binbows.exe
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release_binbows
                  path: release_binbows.exe
    release:
        runs-on: ubuntu-latest
        needs: [build-mac, build-binbows]
        steps:
            - uses: actions/checkout@v2
            - name: Download Mac artifact
              uses: actions/download-artifact@v4
              with:
                  name: release_osx
                  path: release_osx
            - name: Download binbows artifact
              uses: actions/download-artifact@v4
              with:
                  name: release_binbows
                  path: release_binbows
            - name: ls
              run: ls
#            - name: Release
#              uses: softprops/action-gh-release@v1
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              with:
#                  files: "release_osx/**"
#                  tag_name: ${{ github.event.inputs.version }}
#                  name: ${{ github.event.inputs.version }}